# Generated by Django 3.0.8 on 2020-08-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(default='', max_length=124, verbose_name='Краткое название')),
                ('long_title', models.CharField(default='', max_length=124, verbose_name='Полное название')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания организации')),
                ('parent_organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ParentOrg', to='Organization.Organization', verbose_name='Вышестоящая организация')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ('short_title',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=124, verbose_name='Отдел')),
                ('abbreviation', models.CharField(default='', max_length=16, verbose_name='Аббревиатура')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания отдела')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrganizationDep', to='Organization.Organization', verbose_name='Организация')),
                ('parent_department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ParentDep', to='Organization.Department', verbose_name='Вышестоящий отдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ('title',),
                'managed': True,
            },
        ),
    ]
