# Generated by Django 3.1.4 on 2021-02-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workplace', '0012_subnet'),
        ('Violation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ids', models.CharField(default='', max_length=24, verbose_name='id')),
                ('time_stamp', models.CharField(default='', max_length=64, verbose_name='Timestamp')),
                ('code_incident', models.CharField(default='', max_length=64, verbose_name='Code')),
                ('aggregated', models.CharField(default='', max_length=8, verbose_name='Aggregated')),
                ('aggregation_period', models.CharField(default='', max_length=8, verbose_name='Aggregation period')),
                ('source_ip', models.CharField(default='', max_length=24, verbose_name='Src IP')),
                ('source_port', models.CharField(default='', max_length=8, verbose_name='Src port')),
                ('source_MAC', models.CharField(default='', max_length=24, verbose_name='Src MAC')),
                ('destination_ip', models.CharField(default='', max_length=24, verbose_name='Dst IP')),
                ('destination_port', models.CharField(default='', max_length=8, verbose_name='Dst port')),
                ('destination_MAC', models.CharField(default='', max_length=24, verbose_name='Dst MAC')),
                ('protocol', models.CharField(default='', max_length=8, verbose_name='Protocol')),
                ('protocol_name', models.CharField(default='', max_length=8, verbose_name='Protocol name')),
                ('class_incident', models.CharField(default='', max_length=24, verbose_name='Class')),
                ('message_incident', models.CharField(default='', max_length=124, verbose_name='Msg')),
                ('priority', models.CharField(default='', max_length=24, verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Инциент',
                'verbose_name_plural': 'Инциденты',
                'ordering': ('id_ids', 'time_stamp'),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ipviolator',
            name='subnet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Subnet', to='Workplace.subnet'),
        ),
    ]
