# Generated by Django 3.1.4 on 2021-02-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workplace', '0012_subnet'),
        ('Violation', '0002_auto_20210204_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_violation', models.DateField(verbose_name='Дата отчета')),
                ('file_violation', models.FileField(null=True, upload_to='violation/%Y/%m/%d', verbose_name='Файл с инцидентами')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания отчета')),
            ],
            options={
                'verbose_name': 'Отчет о нарушениях',
                'verbose_name_plural': 'Отчеты о нарушениях',
                'ordering': ('date_violation',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Violator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_violator', models.CharField(default='', max_length=24, verbose_name='IP-адрес нарушителя')),
                ('subnet', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Subnet', to='Workplace.subnet')),
                ('violation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DateViolation', to='Violation.reportviolation', verbose_name='Дата отчета')),
            ],
            options={
                'verbose_name': 'IP-адрес нарушителя',
                'verbose_name_plural': 'IP-адреса нарушителей',
                'ordering': ('violation', 'ip_violator'),
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='ipviolator',
            name='date_violation',
        ),
        migrations.RemoveField(
            model_name='ipviolator',
            name='subnet',
        ),
        migrations.DeleteModel(
            name='DateViolation',
        ),
        migrations.DeleteModel(
            name='IPViolator',
        ),
    ]
