# Generated by Django 3.1.4 on 2021-02-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Violation', '0003_auto_20210205_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportviolation',
            name='file_violation',
            field=models.FileField(null=True, upload_to='violation/fc8bb99bc43543e4955a470ec84ab997', verbose_name='Файл с инцидентами'),
        ),
    ]
