# Generated by Django 3.1.4 on 2021-02-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Violation', '0004_auto_20210205_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='violator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IncidentViolator', to='Violation.violator', verbose_name='IP-адрес нарушителя'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id_ids',
            field=models.CharField(default='', max_length=24, verbose_name='id_ids'),
        ),
        migrations.AlterField(
            model_name='reportviolation',
            name='file_violation',
            field=models.FileField(null=True, upload_to='violation/25029c23723d4e8f987ce5aed35e9a0c', verbose_name='Файл с инцидентами'),
        ),
    ]
