# Generated by Django 3.1.4 on 2021-02-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Violation', '0005_auto_20210209_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportviolation',
            name='file_violation',
            field=models.FileField(null=True, upload_to='violation/%Y/%m/%d/918a64724986477986cd4c694da10ec3', verbose_name='Файл с инцидентами'),
        ),
    ]
