# Generated by Django 3.1.4 on 2021-02-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Violation', '0007_auto_20210211_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportviolation',
            name='file_violation',
            field=models.FileField(null=True, upload_to='violation/%Y/%m/%d/7a7f6c82a7734be68aa2cabc074e0096', verbose_name='Файл с инцидентами'),
        ),
        migrations.AlterField(
            model_name='violator',
            name='violation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DateViolation', to='Violation.reportviolation', verbose_name='Дата отчета'),
        ),
    ]
