# Generated by Django 3.1.4 on 2021-02-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Violation', '0008_auto_20210211_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportviolation',
            name='file_violation',
            field=models.FileField(null=True, upload_to='violation/%Y/%m/%d/fe81f77b7b474385b2a6b240e752777a', verbose_name='Файл с инцидентами'),
        ),
    ]
